[package]
name = "harper-core"
version = "0.3.0"
edition = "2021"
description = "The language checker for artists."
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/chilipepperhott/harper"

[dependencies]
hashbrown = "0.14.3"
is-macro = "0.3.0"
itertools = "0.11.0"
once_cell = "1.19.0"
paste = "1.0.14"
pulldown-cmark = "0.9.3"
serde = { version = "1.0.190", features = ["derive"] }
smallvec = "1.12.0"
thiserror = "1.0.56"
