[package]
name = "harper-core"
version = "0.6.2"
edition = "2021"
description = "The language checker for developers."
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/chilipepperhott/harper"

[dependencies]
blanket = "0.3.0"
hashbrown = { version = "0.14.3", features = ["serde"] }
is-macro = "0.3.0"
itertools = "0.11.0"
once_cell = "1.19.0"
paste = "1.0.14"
pulldown-cmark = "0.9.3"
serde = { version = "1.0.190", features = ["derive"] }
smallvec = { version = "1.12.0", features = ["serde"] }
thiserror = "1.0.56"

[dev-dependencies]
divan = "0.1.11"

[[bench]]
name = "parse_demo"
harness = false
