[workspace]
members = [ "harper-cli", "harper-core", "harper-ls", "harper-comments", "harper-wasm", "harper-tree-sitter", "harper-html"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true
