packages:
  - packages/*
  - harper-wasm/pkg
  - packages/harper.js/examples/*

catalog:
  '@typescript-eslint/eslint-plugin': ^8.18.1
  '@typescript-eslint/parser': ^8.18.1
  eslint: ^8.57.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  '@types/node': ^22.13.10
  '@babel/runtime': ^7.26.10
