[package]
name = "harper-literate-haskell"
version = "0.13.0"
edition = "2021"

[dependencies]
harper-core = { path = "../harper-core", version = "0.13.0" }
harper-tree-sitter = { path = "../harper-tree-sitter", version = "0.13.0" }
harper-comments = { path = "../harper-comments", version = "0.13.0" }
itertools = "0.13.0"
paste = "1.0.14"
