[package]
name = "harper-ls"
version = "0.2.0"
edition = "2021"
description = "The language checker for artists."
license = "MIT OR Apache-2.0"

[dependencies]
harper-core = { path = "../harper-core", version = "0.2.0" }
tower-lsp = "0.20.0"
tokio = { version = "1.35.1", features = ["full"] }
clap = { version = "4.4.18", features = ["derive"] }
once_cell = "1.19.0"
