[package]
name = "harper-ls"
version = "0.3.0"
edition = "2021"
description = "The language checker for artists."
license = "MIT OR Apache-2.0"

[dependencies]
harper-core = { path = "../harper-core", version = "0.3.0" }
tower-lsp = "0.20.0"
tokio = { version = "1.35.1", features = ["full"] }
clap = { version = "4.4.18", features = ["derive"] }
once_cell = "1.19.0"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"
tree-sitter-typescript = "0.20.3"
tree-sitter-python = "0.20.4"
tree-sitter-javascript = "0.20.1"
tree-sitter-go = "0.20.0"
tree-sitter-c = "0.20.7"
tree-sitter-cpp = "0.20.3"
tree-sitter-ruby = "0.20.0"
tree-sitter-swift = "0.4.0"
tree-sitter-c-sharp = "0.20.0"
tree-sitter-toml = "0.20.0"
tree-sitter-lua = "0.0.19"
