name: Build Web

on:
  push:
    branches: ['master', 'web-prod']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: nodenv
        uses: nodenv/actions/node-version@v3
      - run: echo "Use Node.js@${{ steps.nodenv.outputs.node-version }}"
      - uses: redhat-actions/buildah-build@v2
        with:
          image: web
          layers: false
          containerfiles: |
            Dockerfile
          build-args: NODE_VERSION=${{ steps.nodenv.outputs.node-version }}
