name: Precommit

on:
  push:
    branches: ["master", "web-prod"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  # Run for 300 times the default
  QUICKCHECK_TESTS: 30000

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Install `pandoc`
        run: sudo apt-get update && sudo apt-get install pandoc -y
      - name: Install `wasm-pack`
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Precommit
        run: just precommit
